# SPDX-FileCopyrightText: 2023 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[tool.bumpversion]
current_version = "0.2.0"

[[tool.bumpversion.files]]
filename = "crates/wasm/examples/version.ts"

[[tool.bumpversion.files]]
filename = "crates/wasm/src/lib.rs"
